# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - git remote remove origin
            - git remote add origin https://narayansharma91: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/github.com/narayansharma91/bitbucket-backup.git
            - git branch -M main
            - git push -u origin main
